import React from 'react';
import { MaterialIcons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';

// Maps prototype icon names (Material Symbols / web kebab-case) to MaterialIcons names.
// All substitutions are centralized here to keep icon changes to a single file.
const ICON_MAP: Record<string, ComponentProps<typeof MaterialIcons>['name']> = {
  'arrow_back': 'arrow-back',
  'arrow-back': 'arrow-back',
  'gavel': 'gavel',
  'menu_book': 'menu-book',
  'menu-book': 'menu-book',
  'event': 'event',
  'location_on': 'location-on',
  'location-on': 'location-on',
  'chevron_right': 'chevron-right',
  'chevron-right': 'chevron-right',
  'star': 'star',
  'star_border': 'star-border',
  'star-border': 'star-border',
  'school': 'school',
  'military_tech': 'military-tech',
  'military-tech': 'military-tech',
  'cake': 'cake',
  'flag': 'flag',
  'workspace_premium': 'workspace-premium',
  'workspace-premium': 'workspace-premium',
  'add': 'add',
  'check_circle': 'check-circle',
  'check-circle': 'check-circle',
  'close': 'close',
  'delete': 'delete',
  'search': 'search',
  'park': 'park',
  'meeting_room': 'meeting-room',
  'meeting-room': 'meeting-room',
  'event_seat': 'event-seat',
  'event-seat': 'event-seat',
  'groups': 'groups',
  'chair': 'chair',
  'format_list_numbered': 'format-list-numbered',
  'format-list-numbered': 'format-list-numbered',
  'ios_share': 'ios-share',
  'ios-share': 'ios-share',
  'verified': 'verified',
  'mic': 'mic',
  'add_circle': 'add-circle',
  'add-circle': 'add-circle',
  'expand_more': 'expand-more',
  'expand-more': 'expand-more',
  'info': 'info',
  'person_add': 'person-add',
  'person-add': 'person-add',
  'remove': 'remove',
  'restart_alt': 'refresh',
  'restart-alt': 'refresh',
  'edit': 'edit',
  'check': 'check',
  'grid_view': 'grid-view',
  'grid-view': 'grid-view',
  'swipe': 'swipe',
  'podium': 'record-voice-over',
  'keyboard_arrow_up': 'keyboard-arrow-up',
  'keyboard-arrow-up': 'keyboard-arrow-up',
  'keyboard_arrow_down': 'keyboard-arrow-down',
  'keyboard-arrow-down': 'keyboard-arrow-down',
  'picture_as_pdf': 'picture-as-pdf',
  'picture-as-pdf': 'picture-as-pdf',
  'image': 'image',
  'description': 'description',
  'share': 'share',
  'download': 'download',
  'wifi_off': 'wifi-off',
  'wifi-off': 'wifi-off',
  'celebration': 'celebration',
  'handshake': 'handshake',
  'local_police': 'local-police',
  'local-police': 'local-police',
  'volunteer_activism': 'favorite',
  'volunteer-activism': 'favorite',
  'church': 'church',
  'diversity_3': 'people',
  'diversity-3': 'people',
  'campaign': 'campaign',
  'sports_kabaddi': 'sports-kabaddi',
  'sports-kabaddi': 'sports-kabaddi',
  'health_and_safety': 'health-and-safety',
  'health-and-safety': 'health-and-safety',
  'shield': 'shield',
  'emoji_events': 'emoji-events',
  'emoji-events': 'emoji-events',
  'check_circle_outline': 'check-circle-outline',
  'check-circle-outline': 'check-circle-outline',
};

type Props = {
  name: string;
  size?: number;
  color?: string;
};

export function Icon({ name, size = 22, color }: Props) {
  const mappedName = (ICON_MAP[name] ?? name) as ComponentProps<typeof MaterialIcons>['name'];
  return <MaterialIcons name={mappedName} size={size} color={color} />;
}
